music_directory     "~/Music"
playlist_directory  "$XDG_CONFIG_HOME/mpd/playlists"
db_file             "$XDG_CONFIG_HOME/mpd/database"
pid_file			"$XDG_RUNTIME_DIR/mpd/mpd.pid"
state_file          "$XDG_RUNTIME_DIR/mpd/state"
sticker_file        "$XDG_CACHE_HOME/mpd/sticker.sql"

audio_output {
    type           "pipewire"
    name           "PipeWire"
}
