# "$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
format = """\
  $directory\
  $git_branch\
  [\uE0B0](bg:#00000000 fg:#89B5FB)\
  \n$character\n\n\n
"""

continuation_prompt = '▶▶ '

#NOTE: you can customize the symbol(s), e.g:
# [character]
# success_symbol = "[  ]($bold fg:#f8f8f2)"
# error_symbol = "[ ➤ ]($bold fg:#fb4934)"

[directory]
disabled = false
format = "[ $path ](fg:#181825 bg:#89B5FB)"
truncate_to_repo = false

[git_branch]
format = "[  $branch ](fg:#181825 bg:#89B5FB)"

