[language-server.biome]
command = "biome"
config  = { provideFormatter = true }
args = ["lsp-proxy"]

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
auto-format = true
language-servers = [ { name = "vscode-json-languageserver", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "html"
scope = "source.html"
file-types = ["html"]
auto-format = true
language-servers = [ "vscode-html-languageserver" ]
