[language-server.biome]
command = "biome"
config  = { provideFormatter = true }
args = ["lsp-proxy"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.css-lsp]
command = "vscode-css-language-server"
config = { provideFormatter = true }
args = ["--stdio"]

[language-server.tailwind-lsp]
command = "tailwindcss-language-server"

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tsx"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "emmet-lsp", "tailwind-lsp" ]

[[language]]
name = "jsx"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "emmet-lsp", "tailwind-lsp" ]

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "html"
scope = "source.html"
file-types = ["html"]
roots = [".git"]
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ "vscode-html-language-server", "emmet-lsp", "css-lsp", "tailwind-lsp" ]

[[language]]
name = "css"
scope = "source.css"
file-types = ["css"]
roots = [".git"]
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ "css-lsp", "tailwind-lsp" ]
